AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dynamo and Lambda Function with Spring boot
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  LambdaDynamoSB:
   Type: AWS::Serverless::Function
   Properties:
    Handler: com.example.demo.config.PersonHandler::handleRequest
    Runtime: java8
    CodeUri: target/LambdaDynamoSpringBoot-0.0.1-SNAPSHOT.jar
    MemorySize: 512
    Role: LambdaDynamoDbRole
    Timeout: 60
    Events:
     GetResource:
       Type: Api
       Properties:
         Path: /{proxy+}
         Method: any
Outputs:
  LambdaDynamoSBFunc:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage'
    Export:
      Name: LambdaDynamoSBFunction         